branches:
  except:
    - gh-pages

language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - openssl aes-256-cbc -K $encrypted_59805aa73fa9_key -iv $encrypted_59805aa73fa9_iv -in development.env.enc -out development.env -d

install: "pip install vizydrop-sdk python-dateutil pytest-envfiles"

script: "py.test ."

notifications:
  slack: targetprocess:3vskJskCGoKESMxPoIPRaOkd